// Generates src/symbols-data.ts: every symbol the APRS symbol tables define, by name.
//
//   node scripts/generate-symbols.mjs <AprsSymbol.Named.cs> <APRS-Symbols.txt>
//
// The names and descriptions are packet.net's (src/Packet.Aprs/AprsSymbol.Named.cs, from the
// symbol table in APRS12c ch. 21 and APRS-Symbols), so the two libraries name symbols alike;
// the names are camelCased here. Which alternate-table symbols take an overlay comes from the
// `#` marks in the GPSxyz column of APRS-Symbols.

import { readFileSync, writeFileSync } from 'node:fs';

const [named, table] = process.argv.slice(2);
if (!named || !table) {
  console.error('usage: node scripts/generate-symbols.mjs <AprsSymbol.Named.cs> <APRS-Symbols.txt>');
  process.exit(2);
}

const unxml = (s) => s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&');
const unescapeChar = (s) => (s.startsWith('\\') ? s.slice(1) : s);

const cs = readFileSync(named, 'utf8');
const re = /\/\/\/ <summary>(.*?): <c>.*?<\/c>\.<\/summary>\s*\n\s*public static AprsSymbol (\w+) => new\('(\\\\|.)', '(\\.|.)'\);/g;
const symbols = [];
for (const m of cs.matchAll(re)) {
  const table = m[3] === '\\\\' ? '\\' : m[3];
  const code = unescapeChar(m[4]);
  const name = m[2][0].toLowerCase() + m[2].slice(1);
  symbols.push({ name, table, code, description: unxml(m[1]) });
}
const declared = (cs.match(/public static AprsSymbol /g) ?? []).length;
if (symbols.length !== declared) throw new Error(`parsed ${symbols.length} of ${declared} symbols`);

const text = readFileSync(table, 'utf8');
let overlays = '';
for (const line of text.split('\n')) {
  for (const m of line.matchAll(/\\(\S)\s+([A-Z][A-Z0-9])(#?)\s+(\d\d)\b/g)) {
    if (m[3] === '#') overlays += m[1] === '’' ? "'" : m[1];
  }
}

const esc = (s) => JSON.stringify(s);
let out = `// Generated by scripts/generate-symbols.mjs; do not edit by hand. Every symbol the APRS symbol
// tables define (APRS12c ch. 21, APRS-Symbols), named as packet.net's AprsSymbol.Named.cs names
// them, with the description from the table.

/** A named symbol: its table, code and description. */
export interface NamedSymbolEntry {
  readonly table: string;
  readonly code: string;
  readonly description: string;
}

/** Every named symbol. */
export const NAMED_SYMBOLS = {
`;
for (const s of symbols) out += `  ${s.name}: { table: ${esc(s.table)}, code: ${esc(s.code)}, description: ${esc(s.description)} },\n`;
out += `} as const satisfies Record<string, NamedSymbolEntry>;

/** Alternate-table symbol codes that take an overlay character (marked # in APRS-Symbols). */
export const OVERLAY_CODES = ${esc(overlays)};
`;
writeFileSync(new URL('../src/symbols-data.ts', import.meta.url), out);
console.log(`src/symbols-data.ts: ${symbols.length} symbols, ${overlays.length} overlay codes`);
